### ISSUE TITLE
about the framework

### ISSUE THREAD

**Issue by 1090118235** [Torbjorn1997/PIViT#1]
Hello, author.  I would like to ask you about the number of channels in your model feature map and deformation field in Figure 2.For example, Fm3 and φ3?

**Comment by Torbjorn1997** [comment]
I'm sorry to have just seen your question, in PIViT, the number of convolution channels is 32 except for the convolution channel used to get the deformation field which is 3. I've been busy with another work lately and the code for PIViT will be made public soon.
Fm3 = 32 
φ3 = 3
