### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by yesstarA** [Torbjorn1997/PIViT#3]
I'm wondering if it's possible to run this network on a GTX3090, (160, 192, 224) image?

**Comment by Torbjorn1997** [comment]
Of course, I assume you are referring to the OASIS dataset. I just did a simple training on a GTX3090 . The GPU memory usage is 4911MB and each step takes about 0.6s.
![image](https://github.com/Torbjorn1997/PIViT/assets/28394656/25678226-0833-43a9-9cbb-49ec42a70199)
![image](https://github.com/Torbjorn1997/PIViT/assets/28394656/ab7dc763-a5f2-45a9-8395-3cd4beb16dc2)
