### ISSUE TITLE
loss值不降低

### ISSUE THREAD

**Issue by SadInSummer** [Torbjorn1997/PIViT#4]
这损失值怎么降反升啊，是我的问题吗，可是我啥都没有改呀，还是说本来就这样

**Comment by Torbjorn1997** [comment]
理论上损失值应该是负的，而且随着训练越来越小，可能是你的数据或者其他原因的问题，在没有更多信息的情况下我也不能确定

**Comment by SadInSummer** [comment]
就是，我现在还没有用自己的数据，就是用你提供那两个的，就是我直接复现，这个loss值就是来回震荡。loss是负的我知道，文章中的损失函数里指明了这个。我不知道这个震荡是属于正常现象还是啥，学习率什么的我都没有修改

**Comment by Torbjorn1997** [comment]
> 就是，我现在还没有用自己的数据，就是用你提供那两个的，就是我直接复现，这个损失值就是来回震荡的。损失是负的我知道，文章中的损失函数里指明了这个。我不知道这个震荡是属于正常现象还是啥，学习率什么的我都没有修改

这两张图是用来测试的，为什么要用来训练，两张图怎么训练网络。。。

**Comment by Torbjorn1997** [comment]
训练用的MindBoggle数据集，你可以下载这个数据集试试

**Comment by SadInSummer** [comment]
可以分享一下你训练数据的目录结构吗，谢谢，就是 是一个data文件下直接有很多数据还是一个data文件夹下有很多子文件夹，每个文件夹里有两个数据呢

**Comment by Torbjorn1997** [comment]
> 可以分享一下你训练数据的目录结构吗，谢谢，就是 是一个data文件下直接有很多数据还是一个data文件夹下有很多子文件夹，每个文件夹里有两个数据呢

如果你指的是训练时的文件夹，那么他和PIViT/data/vol/是一样的，所有训练数据都放在vol文件夹下，但是不只有两个数据而是训练集的全部数据都在这里

**Comment by SadInSummer** [comment]
好，谢谢。我用测试数据就是想看看这个网络怎么运行的，我去找训练集试试
