### ISSUE TITLE
测试代码

### ISSUE THREAD

**Issue by SadInSummer** [Torbjorn1997/PIViT#5]
作者你好，我想问一下这个测试代码中的npz文件是什么呢？起到什么作用呢

**Comment by Torbjorn1997** [comment]
是标签id，用来算dice，你也可以用np.unique()实现

**Comment by SadInSummer** [comment]
大佬，可以详细说一下嘛，新手不太懂这个，我该怎么生成这个标签的呢。我看标签长这个样子。我查看了npz文件的具体值，是160，然后这些标签id最大的可能有1024，1025这些，小的也有个位数，这代表我的真实标签有1025个类别这么多吗
![image](https://github.com/user-attachments/assets/4d195425-d716-4ef1-830e-2beb824c6053)

**Comment by Torbjorn1997** [comment]
> 大佬，可以详细说一下嘛，新手不太懂这个，我该怎么生成这个标签的呢。我看标签长这个样子 ![image](https://private-user-images.githubusercontent.com/94618702/387156895-4d195425-d716-4ef1-830e-2beb824c6053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjMwMjMsIm5iZiI6MTczMTkyMjcyMywicGF0aCI6Ii85NDYxODcwMi8zODcxNTY4OTUtNGQxOTU0MjUtZDcxNi00ZWYxLTgzMGUtMmJlYjgyNGM2MDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA5Mzg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMzI1MWVjN2FmYjQxZDNmZDY1YzFhNTdmMGUwNTkyNzE5ZThiYWJiZDIwNWZmMGYzYTVjZGEyOGQ0Y2IwMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iUX92HTZ-0Z9fFKm_zHEX3SKyZwQWsvPCMSQkDGWMnY)

首先读取这个label的nii.gz文件，然后用np.unique()查看这个文件里有多少个label，把这些label组成的数组存到这个npz文件中，就拿到我提供的npz了

**Comment by SadInSummer** [comment]
好，我去研究一下，真的非常感谢了

**Comment by Torbjorn1997** [comment]
> 大佬，可以详细说一下嘛，新手不太懂这个，我该怎么生成这个标签的呢。我看标签长这个样子。我查看了npz文件的具体值，是160，然后这些标签id最大的可能有1024，1025这些，小的也有个位数，这代表我的真实标签有1025个类别这么多吗 ![image](https://private-user-images.githubusercontent.com/94618702/387156895-4d195425-d716-4ef1-830e-2beb824c6053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjMwNjgsIm5iZiI6MTczMTkyMjc2OCwicGF0aCI6Ii85NDYxODcwMi8zODcxNTY4OTUtNGQxOTU0MjUtZDcxNi00ZWYxLTgzMGUtMmJlYjgyNGM2MDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA5MzkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkOGE4ZjdjNjhiMDI2MmU1MWY0Njg4ODMwZjE1ZjQ1NjAyNWEwZWU4YmZiNGQ1MWFiZTNlZDk4NDhkMjQwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t_fysLUA6dKUaZdrTvEEGuf9f1QqXL23n39kRKQEEt8)

没有1025，中间是断掉的，好像是106个，所以要用函数查看出来有哪些。这些label逐个算dice的均值是配准的dice结果

**Comment by SadInSummer** [comment]
应该把0去掉对吧，去掉0是106个，我读出来是有1025的，我看了一下你提供的这个 是有1025的，没有0，是106个
下面是我读出来的这个结果。这个存储顺序是版本不影响的对吧。谢谢
![image](https://github.com/user-attachments/assets/2fab91ae-4971-4b34-9e3a-2c3ba2ae8856)

![image](https://github.com/user-attachments/assets/29734ba2-56b5-40cd-96c6-7836e908dc7c)

**Comment by SadInSummer** [comment]
还有一个问题，大佬。就是我们项目上有MRI的nii，我有什么软件或者算法可以得到类似于这样的分割结果吗
![image](https://github.com/user-attachments/assets/7d6cda5b-2179-4d42-a42a-5320fc057ffa)

**Comment by Torbjorn1997** [comment]
> 应该把0去掉对吧，去掉0是106个，我读出来是有1025的，我看了一下你提供的这个 是有1025的，没有0，是106个 下面是我读出来的这个结果。这个存储顺序是版本不影响的对吧。谢谢 ![image](https://private-user-images.githubusercontent.com/94618702/387188604-2fab91ae-4971-4b34-9e3a-2c3ba2ae8856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTg3NjksIm5iZiI6MTczMTk5ODQ2OSwicGF0aCI6Ii85NDYxODcwMi8zODcxODg2MDQtMmZhYjkxYWUtNDk3MS00YjM0LTllM2EtMmMzYmEyYWU4ODU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA2NDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YjU2ODAwYzJhN2VmNWRjNGUxYjE3ZjEwYzFlY2I3ZjVmODJhZTEyZjE3ZWU0ZmJiNDliNTIxNzgyYjgxNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k4R5yPo9OzHuwFPbNnisCfQnjmoUTGN_eCrOyd2eHcI)
> 
> ![image](https://private-user-images.githubusercontent.com/94618702/387188547-29734ba2-56b5-40cd-96c6-7836e908dc7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTg3NjksIm5iZiI6MTczMTk5ODQ2OSwicGF0aCI6Ii85NDYxODcwMi8zODcxODg1NDctMjk3MzRiYTItNTZiNS00MGNkLTk2YzYtNzgzNmU5MDhkYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA2NDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMjRiMzk2YTFjMGFiNTkxODRlZTk3YjM3NmI4NTI3OTE4MDAyYjVjMTNiOWQwMDU2ZWU2MzExNjQzNzAwOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RqvK8J91Vvkej7pgTkBzfWch79DNQVc2nXM9QB6lWko)

是的，0是背景，不会用来算dice，顺序也没有影响，因为要算所有编号的均值

**Comment by Torbjorn1997** [comment]
> 还有一个问题，大佬。就是我们项目上有MRI的nii，我有什么软件或者算法可以得到类似于这样的分割结果吗 ![image](https://private-user-images.githubusercontent.com/94618702/387207467-7d6cda5b-2179-4d42-a42a-5320fc057ffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTg3NjksIm5iZiI6MTczMTk5ODQ2OSwicGF0aCI6Ii85NDYxODcwMi8zODcyMDc0NjctN2Q2Y2RhNWItMjE3OS00ZDQyLWE0MmEtNTMyMGZjMDU3ZmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA2NDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlM2M3MDVlYmMyMjc4NTkzYWRjYjRkZDMyNDY4MmJkMGYxN2Y5NmFjZjJlZmE5ODI0YjBkN2YzNzRmMmRlNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.goUpXvdT9CMBh_wHCi7EVZu62yQpCDQP5pACoQ-9aNY)

你可以尝试一下nnunet，不过我不确定你们的任务具体情况，如果是一个无监督分割任务我不是很了解，或许你可以试试medsam。实验中mindboggle的解剖标签是手动标注的。

**Comment by SadInSummer** [comment]
好的，谢谢

**Comment by SadInSummer** [comment]
我如果用自己的数据然后用你提供的预训练参数。我把我的nii改为了相同的尺寸，但是，我发现预测出来的只有几个白点，并不能得到形变图像，这是因为我们数据分布不同的原因吗，我用的测试图像是mrit1.

**Comment by Torbjorn1997** [comment]
> 我如果用自己的数据然后用你提供的预训练参数。我把我的nii改为相同的尺寸，但是，我发现预测出来的只有几个白点，并且不能得到形变图像，因为这是我们的数据分配不同的原因吗，我用的测试图像是mrit1。

我提供的模型也是t1数据上训练的，也许你可以对比一下你的数据和我提供的测试数据看一下。在调整图像尺寸时，我保持图像的voxel size始终是1mm，通过裁剪的方式调整到该大小。不过我觉得最有可能的问题是你的数据没有做归一化0-1的操作。我的模型是在数据集归一化成0-1后训练的。

**Comment by SadInSummer** [comment]
这个voxel size指的是啥呀，我的数据的确没有归一化，还有就是在归一化之后是不是也不用调整窗宽窗位了

**Comment by Torbjorn1997** [comment]
> 这个voxel size指的是啥呀，我的数据的确没有归一化，还有就是在归一化之后是不是也不用调整窗宽窗位了

就是spacing=1mm，我们只做了归一化操作

**Comment by SadInSummer** [comment]
我查看了一下，Voxel size: (1.0, 1.0, 1.0) 应该是1没错。 我再试试归一化

**Comment by SadInSummer** [comment]
大佬，我确认一下，如果我resize但是保证spacing不变，我原图像会被丢失调一点边边上的信息对吧
![image](https://github.com/user-attachments/assets/dff10b47-6228-4e79-af33-fb33f85457eb)

**Comment by SadInSummer** [comment]
![image](https://github.com/user-attachments/assets/d02e2823-98a1-4ccc-9d5c-552d8dbe5a25)
大佬，我确认一下，如果我resize但是保证spacing不变，我原图像会被丢失调一点边边上的信息对吧
image

**Comment by Torbjorn1997** [comment]
> ![image](https://private-user-images.githubusercontent.com/94618702/388109613-d02e2823-98a1-4ccc-9d5c-552d8dbe5a25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDk1MDEsIm5iZiI6MTczMjEwOTIwMSwicGF0aCI6Ii85NDYxODcwMi8zODgxMDk2MTMtZDAyZTI4MjMtOThhMS00Y2NjLTlkNWMtNTUyZDhkYmU1YTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDEzMjY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMmYzM2U5NmJlOGY5YTUyOTM2ZjQ1Mzg4ZTc1NjAwYmQ2MDcyMjQzMzk1MzE0NTRhODUxOTMwYTQwMTM3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wF3OIy_avm_u72GkJPRRcmmo-bSNesWNVb0cTTSiZ7U) 大佬，我确认一下，如果我resize但是保证spacing不变，我原图像会被丢失调一点边边上的信息对吧 image

我比较好奇你的下界边缘是否有信息呢，如果没有的话也许可以通过裁剪下边缘避免上部分信息的缺失？我在裁剪的时候只裁剪没有灰度的区域。现在这样的裁剪我感觉不是很合适，缺失了一些信息，如果没办法改变裁剪策略你可以用这个数据试一下我的预训练模型能不能用于你的配准需求。对于你的数据，你可以重新根据这个数据集有信息的区域的最大范围重新设置一个裁剪区域，只要保证尺寸是32的倍数就可以。然后用你的数据重新训练一个网络，我们的网络是无监督的，不需要任何标签就可以训练配准网络。

**Comment by SadInSummer** [comment]
如果使用你的网络进行训练的话，只要保证三个size都是32的倍数就可以是吗？测试的话是不是必须保证尺寸为（160,192,160）呀？这个数据的下边缘应该也没什么信息吧，就是我是为了符合你的测试的那个尺寸才进行这样剪裁的。你说的这个没有灰度的区域意思是nii中最边上的那些没内容的全黑的slice是吗？可以提供这个剪裁的代码不，万分感谢

**Comment by SadInSummer** [comment]
其实我一开始想的是，这个nii虽然看起来有300,300,300这样的尺寸，但是实际上他很多边上的黑色的，我是想不改变有内容的部分，直接给他拿出来，但是我没有找到正确的代码，就用了一个resize的代码，但是这个resize的代码会改变spacing的。我不知道我想的取出来这个操作叫什么操作，不知道该怎么搜，不知道能用什么工具完成这件事

**Comment by Torbjorn1997** [comment]
> 如果使用你的网络进行训练的话，只要保证三个size都是32的倍数就可以是吗？测试的话是不是必须保证尺寸为（160,192,160）呀？这个数据的下边缘应该也没什么信息吧，就是我是为了符合你的测试的那个尺寸才进行这样剪裁的。你说的这个没有灰度的区域意思是nii中最边上的那些没内容的全黑的slice是吗？可以提供这个剪裁的代码不，万分感谢

是的，只要都是32的倍数就可以，测试和你训练的大小一样，只有调用我的预训练权重的时候才要保证是（160,192,160）

我这里说的没有信息就是说整个slice都是0，这样的部分裁掉比较合适

**Comment by Torbjorn1997** [comment]
> 其实我一开始想的是，这个nii虽然看起来有300,300,300这样的尺寸，但是实际上他很多边上的黑色的，我是想不改变有内容的部分，直接给他拿出来，但是我没有找到正确的代码，就用了一个resize的代码，但是这个resize的代码会改变spacing的。我不知道我想的取出来这个操作叫什么操作，不知道该怎么搜，不知道能用什么工具完成这件事

这个操作叫crop，也就是我说的裁剪，我今天正好写了一下这个代码，在我的数据上没什么问题，你可以试试


```python
import os
import nibabel as nib
import numpy as np


# 裁剪函数：保持原始图像的内容居中
def crop_image_centered(image, target_size):
    """
    裁剪图像到目标大小，并尽量保持原图中心位置。

    参数:
    - image: 输入的3D图像 (numpy array)
    - target_size: 目标大小 (depth, height, width)

    返回:
    - cropped_image: 裁剪后的图像
    """
    original_shape = image.shape
    target_depth, target_height, target_width = target_size

    # 找到非零区域
    def find_bounds(data):
        non_zero = np.where(data > 0)
        min_index = np.min(non_zero)
        max_index = np.max(non_zero) + 1
        return min_index, max_index

    z_min, z_max = find_bounds(np.max(np.max(image, axis=1), axis=1))
    y_min, y_max = find_bounds(np.max(np.max(image, axis=0), axis=1))
    x_min, x_max = find_bounds(np.max(np.max(image, axis=0), axis=0))

    # 计算非零区域中心
    z_center = (z_min + z_max) // 2
    y_center = (y_min + y_max) // 2
    x_center = (x_min + x_max) // 2

    # 计算裁剪区域的起始和结束位置
    z_start = max(0, z_center - target_depth // 2)
    y_start = max(0, y_center - target_height // 2)
    x_start = max(0, x_center - target_width // 2)

    z_end = z_start + target_depth
    y_end = y_start + target_height
    x_end = x_start + target_width

    # 确保裁剪范围不超出原始图像
    z_start = max(0, min(z_start, original_shape[0] - target_depth))
    y_start = max(0, min(y_start, original_shape[1] - target_height))
    x_start = max(0, min(x_start, original_shape[2] - target_width))

    z_end = z_start + target_depth
    y_end = y_start + target_height
    x_end = x_start + target_width

    # 裁剪图像
    cropped_image = image[z_start:z_end, y_start:y_end, x_start:x_end]
    return cropped_image


# 归一化函数
def normalize_image(image, normalization_type="minmax"):
    """
    对图像进行归一化处理。

    参数:
    - image: 输入的3D图像 (numpy array)
    - normalization_type: 归一化类型 ("minmax" 或 "zscore")

    返回:
    - normalized_image: 归一化后的图像
    """
    if normalization_type == "minmax":
        # 将图像值归一化到 [0, 1]
        min_val = np.min(image)
        max_val = np.max(image)
        if max_val > min_val:  # 避免除以零
            normalized_image = (image - min_val) / (max_val - min_val)
        else:
            normalized_image = image  # 如果最大值等于最小值，不做归一化
    elif normalization_type == "zscore":
        # Z-Score 标准化 (均值为0，标准差为1)
        mean_val = np.mean(image)
        std_val = np.std(image)
        if std_val > 0:  # 避免除以零
            normalized_image = (image - mean_val) / std_val
        else:
            normalized_image = image  # 如果标准差为0，不做归一化
    else:
        raise ValueError("Unsupported normalization type. Choose 'minmax' or 'zscore'.")

    return normalized_image

# 遍历文件夹并处理每个 nii.gz 文件
data_path = r"/data/LUMIR_L2R24_TrainVal/imagesTr"
target_size = (160, 192, 160)
output_root = r"/data/lumir"

for root, dirs, files in os.walk(data_path):
    for file in files:
        if file.endswith(".nii.gz"):
            file_path = os.path.join(root, file)

            # 加载 NIfTI 文件
            nii_image = nib.load(file_path)
            image_data = nii_image.get_fdata()  # 获取图像数据

            print(f"正在处理文件: {file}")
            print(f"原始图像形状: {image_data.shape}")

            # 裁剪图像
            cropped_data = crop_image_centered(image_data, target_size)
            print(f"裁剪后图像形状: {cropped_data.shape}")

            # 归一化图像
            normalized_data = normalize_image(cropped_data, normalization_type="minmax")
            print(f"归一化完成，数据范围: [{np.min(normalized_data)}, {np.max(normalized_data)}]")

            # 保存裁剪后的文件
            cropped_nii = nib.Nifti1Image(normalized_data, nii_image.affine, nii_image.header)
            output_path = os.path.join(output_root, f"{file}")
            nib.save(cropped_nii, output_path)
            print(f"裁剪后的文件已保存到: {output_path}")
```

**Comment by Torbjorn1997** [comment]
排版怪怪的，不知道怎么搞

**Comment by SadInSummer** [comment]
感谢大佬了，我正在问gpt，我试试你的代码

**Comment by SadInSummer** [comment]
是可以的，感谢大佬分享

**Comment by Torbjorn1997** [comment]
> 是可以的，感谢大佬分享

好的，如果配准没问题的话就更好了，你也可以试试我们在CVPR2024提出的IIRP-Net，PIViT主要针对大型变，在细节上可能有所缺失，IIRP-Net理论上效果更好。

**Comment by SadInSummer** [comment]
立马就去搜。

**Comment by SadInSummer** [comment]
您好，如果我想存这个flow的话，我直接存下来是个(3, 160, 192, 160)这样的尺寸的nii，我直接用itk打开就是一个不正常的竖条。一般来说如何打开这个文件，还是只能通过切片查看二维图像呀。我看论文中是一个二维的展示效果

**Comment by Torbjorn1997** [comment]
> 您好，如果我想存这个flow的话，我直接存下来是个(3, 160, 192, 160)这样的尺寸的nii，我直接用itk打开就是一个不正常的竖条。一般来说如何打开这个文件，还是只能通过切片查看二维图像呀。我看论文中是一个二维的展示效果

transpose或者permute成（160，192，160，3）的形状就能用itk打开了

**Comment by SadInSummer** [comment]
好的谢谢

**Comment by SadInSummer** [comment]
![image](https://github.com/user-attachments/assets/207f4bf2-2fe0-44af-b764-45ab89e0f768)
这种情况是正常的嘛，没有内容的部分也是灰色的，是不是我原始数据的背景值不为0，但是进行了归一化。还是说这就是正常的结果呀

**Comment by Torbjorn1997** [comment]
> ![image](https://private-user-images.githubusercontent.com/94618702/388540804-207f4bf2-2fe0-44af-b764-45ab89e0f768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxOTczOTEsIm5iZiI6MTczMjE5NzA5MSwicGF0aCI6Ii85NDYxODcwMi8zODg1NDA4MDQtMjA3ZjRiZjItMmZlMC00NGFmLWI3NjQtNDVhYjg5ZTBmNzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDEzNTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyOWQyNjMwZWViNTc2ZDVkYTFiZmM0YzZiOTE4NjQ1NjBkMDBjOGNmYTIwMjY4YTg4NWZjNTUyZGI4MGQ0MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YnDrqkEBfgn-9UpremcEp6sZoQr2xBmpYLb8OgnPFNA) 这种情况是正常的嘛，没有内容的部分也是灰色的，是不是我原始数据的背景值不为0，但是进行了归一化。还是说这就是正常的结果呀

这就是正常的，因为形变场正负表示方向，没有形变的地方就是0，所以显示的是灰色。

**Comment by SadInSummer** [comment]
好的  懂了，谢谢了
